apiVersion: apps/v1
kind: Deployment
metadata: 
  name: auth-service-depl
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: auth-service
  template: 
    metadata: 
      labels: 
        app: auth-service
    spec: 
      containers: 
        - name: auth-service # container name
          image: bankole2000/auth-service # image name - eg bankole2000/auth-service
          imagePullPolicy: Never