apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
        - name: notifications
          image: bankole2000/notification-service
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: notifications-clusterip-srv
# spec:
#   selector:
#     app: notifications
#   ports:
#     - name: notifications
#       protocol: TCP
#       port: 4001
#       targetPort: 4001
