apiVersion: v1
kind: Service
metadata:
  name: notifications-srv
spec:
  type: NodePort
  selector:
    app: notifications
  ports:
    - name: notifications
      protocol: TCP
      port: 4001
      targetPort: 4001
